### ISSUE TITLE
import-item from windows to *nix

### ISSUE THREAD

**Issue by igord** [Backbase/bb-cli#125]
import-item will use native windows lib to create zip
That is apparently a problem as file paths inside a zip are not preserved properly
http://unix.stackexchange.com/questions/166159/convert-a-windows-created-zip-to-linux-internal-paths-issue
When we import a zip file created on windows, or import-item remotely from windows to *nix machine, it will fail.

The solution will be to use 7zip on windows, but that will require 7zip to be installed.

**Comment by craigwalkeruk** [comment]
@igord , you libs used current look to be doing it own compression, have you tried to use the windows native DOS command to zip.upzip?

**Comment by igord** [comment]
@craigwalkeruk are they available on all versions of windows that we support? we are using shelljs already so I could try...

**Comment by craigwalkeruk** [comment]
from windows 3.11 to 10.. i think. Even i expect windows powershell will do the same shell command

**Comment by bartveenstra** [comment]
Is there a solution for this already?

**Comment by dirkgietelink** [comment]
Some OOTB thinking... I've seen cases before, where zipping on windows causes very restrictive file permissions inside the archive once extracted on *nix systems. So, it might be the case the import fails because extraction goes fine, but the user not even having read permissions on some extracted files. So chmod might be needed. @bartveenstra have you check this?

**Comment by bartveenstra** [comment]
The problem is that it fails to do an import-item on windows to windows. No Unix paths yet. What we might think is the maximum path lenght in Windows. It was failing on importing jquery which has crazy nested directories..
